<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
		
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>edu.kit.ipd.sdq.kamp</groupId>
		<artifactId>parent</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>
	<artifactId>bundles</artifactId>
	<packaging>pom</packaging>
	
	<modules>
		<module>edu.kit.ipd.sdq.kamp</module>
		<module>edu.kit.ipd.sdq.kamp.model.modificationmarks</module>
		<module>edu.kit.ipd.sdq.kamp.model.modificationmarks.edit</module>
		<module>edu.kit.ipd.sdq.kamp.model.modificationmarks.editor</module>
		<module>Toometa/de.uka.ipd.sdq.dsexplore.qml.dimensiontypes</module>
		<module>Toometa/de.uka.ipd.sdq.dsexplore.qml.dimensiontypes.edit</module>
		<module>Toometa/de.uka.ipd.sdq.dsexplore.qml.dimensions</module>
		<module>Toometa/de.uka.ipd.sdq.dsexplore.qml.dimensions.edit</module>
		<module>Toometa/de.uka.ipd.sdq.dsexplore.qml.units</module>
		<module>Toometa/de.uka.ipd.sdq.dsexplore.qml.units.edit</module>
		<module>Toometa/de.uka.ipd.sdq.namedelement</module>
		<module>Toometa/de.uka.ipd.sdq.namedelement.edit</module>
		<module>Toometa/toometa.archoptions</module>
		<module>Toometa/toometa.decisions</module>
		<module>Toometa/toometa.decisions.edit</module>
		<module>Toometa/toometa.effects</module>
		<module>Toometa/toometa.effects.edit</module>
		<module>Toometa/toometa.glossary</module>
		<module>Toometa/toometa.glossary.edit</module>
		<module>Toometa/toometa.options</module>
		<module>Toometa/toometa.options.edit</module>
		<module>Toometa/toometa.pcmbpoptions</module>
		<module>Toometa/toometa.pcmarchoptions</module>
		<module>Toometa/toometa.qualities</module>
		<module>Toometa/toometa.qualities.edit</module>
		<module>Toometa/toometa.relations</module>
		<module>Toometa/toometa.relations.edit</module>
		<module>Toometa/toometa.requirements</module>
		<module>Toometa/toometa.requirements.edit</module>
	</modules>
	
</project>
